apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ofq4ilonh-python 
  janus-idp.io/tekton: ofq4ilonh-python
  backstage.io/kubernetes-id: ofq4ilonh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ofq4ilonh-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml